# docker-compose up
# This command builds (use only if no code changes)

# docker-compose up --build
# This command builds (use only if code changes)

version: "3.9"

services:
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"